### ISSUE TITLE
Be specific about which JSON Schema drafts are supported

### ISSUE THREAD

**Issue by jakubklimek** [ISAITB/json-validator#1]
I did not find a list of supported [JSON Schema drafts](https://json-schema.org/specification.html#migrating-from-older-drafts) in the documentation.
Therefore, I assumed that all of them are supported, which, unfortunately, is not the case, at least for my versions `2019-09` and `2020-12` as I get:
```
Error while parsing JSON schema: [2,61][/$schema] Unsuppoted metaschema: "https://json-schema.org/draft/2019-09/schema".
Error while parsing JSON schema: [2,61][/$schema] Unsuppoted metaschema: "https://json-schema.org/draft/2020-12/schema".
```
In all the examples, `draft-07` from 2018 is used - is it the only one supported?

**Comment by costas80** [comment]
Hi @jakubklimek . Indeed, this is something we should document. Currently the JSON validator supports only versions `Draft-07`, `Draft-06`, and `Draft-04`; so not the latest `V2019-09` and `V2020-12` versions.

Having said this, we are planning to upgrade the library used by the validator to support all specification versions (this has not been prioritised yet as support for the latest versions has not been requested). Could you give an indication of when you would be needing this?

**Comment by jakubklimek** [comment]
We use 2019-09 and 2020-12 JSON Schemas already. I was just curious whether the ITB could be used for validation in addition to/instead of the validators that we use currently, which, for us, it cannot in its current state. I would use it otherwise. But there is no deadline for my case

**Comment by costas80** [comment]
Ok thanks for the feedback. We will bump up the priority of this and include support for the latest specification versions in the next release of the validator. This should proceed quite fast as we do not implement the specification support ourselves but rather use a separate validation library (which we have planned to replace for some time now exactly because of this issue).

I'll follow up here when this becomes available.

**Comment by costas80** [comment]
Hi @jakubklimek , we just added support for the latest Core Drafts v2019-09 and v2020-12. Also, as per this issue, the repo's README is updated to mention the supported versions.

If you have the chance to use the validator feel free to share any feedback you may have (almost all users are still using older drafts). The simplest way to use it is [via Docker](https://hub.docker.com/r/isaitb/json-validator) where the **latest** tag reflects the current repo's master branch. Note that we will also be publishing soon a "milestone" release to allow referring to a stable tag.
