### ISSUE TITLE
Support for JSON Schema drafts 2019-09 and 2020-12

### ISSUE THREAD

**Issue by jakubklimek** [ISAITB/json-validator#2]
It would be nice to support the more up-to-date JSON Schema drafts, specifically, 2019-09 and 2020-12 + monitor draft-next for when it will be released.

**Comment by costas80** [comment]
Hi @jakubklimek . Indeed, this has been on our backlog but not prioritised yet as it had not been requested.

Do you have an idea of when more/less you would be interested in having this available (if you have specific planning needs on your end)?

**Comment by costas80** [comment]
See also #1

**Comment by costas80** [comment]
The validator has been updated to support also Core Drafts v2019-09 and v2020-12.
