### ISSUE TITLE
Use-case: zero config docker

### ISSUE THREAD

**Issue by jakubklimek** [ISAITB/json-validator#3]
My use case was to just spin up the validator and provide custom (any) JSON schema and instance to be validated via the Web UI. This could be a docker one-liner. Unfortunately, the docker distribution requires some files (config and schemas) to be provided on startup and refuses to start without it - complains about the resources folder being empty. Could this be added for vases where no configuration is necessary?

**Comment by costas80** [comment]
Excellent point @jakubklimek . This is indeed an update we were planning to do shortly given that the validator in its "as-is" status needs to be supplied with a configuration (the files you mention). We were planning on simply preconfiguring it with the existing configuration for our [generic JSON validator instance](https://www.itb.ec.europa.eu/json/any/upload) which does exactly what you suggest. We had planned to do this for all our validators actually (XML, RDF and CSV apart from the JSON one).

**Comment by costas80** [comment]
The update to allow starting up a generic validator without any configuration is now available (the updated behaviour is documented in the README).
