### ISSUE TITLE
Error in validation : schema is unrecognizable.

### ISSUE THREAD

**Issue by EliottPaillard** [ISAITB/json-validator#5]
Hello!

When trying to validate this JSON document :
[test.json](https://github.com/ISAITB/json-validator/files/15146644/test.json)

using this schema :
[AirQualityObserved.json](https://github.com/ISAITB/json-validator/files/15146647/AirQualityObserved.json)

I expect a failure and two errors related to missing required properties.

But an error occurs : "An error occurred during the validation: 'http://json-schema.org/schema#' is unrecognizable schema."

I solved it by changing the "http://json-schema.org/schema#" by "https://json-schema.org/draft/2020-12/schema" in the schema but also in all the ref schemas mentioned but this feels not really convenient.

My question is : Do I need to change all my schemas and the ref ones because they're not up-to-date ?

**Comment by costas80** [comment]
Hi @EliottPaillard. Indeed you need to set the `$schema` property with the specification draft your schema follows. This is needed to define a valid JSON schema as per the JSON Schema spec (see [here](https://json-schema.org/learn/getting-started-step-by-step#create)), its not a requirement imposed by the validator. JSON schema draft versions have quite significant differences between them that are often not backwards compatible so you should anyway set the draft version you follow to make it explicit.

So yes, you need to set this explicitly for all schemas (referred to or not).

**Comment by EliottPaillard** [comment]
Hello,
thank you for your quick answer.
I have another question. 
In my testsuite I have a testcase that import a json schema embedded in the zip. Is it possible to use the $ref calling other schemas also in the zip? I've found that "file:///path/to/file" could be use to reference a local file but I couldn't get it to work so far.

**Comment by costas80** [comment]
Hi @EliottPaillard. Was the solution I mentioned in the previous comment ok for you? (asking to see if we can close this issue)

**Comment by EliottPaillard** [comment]
Hey,
For now we've found another way to deal with it.
However I'll keep in mind testing your solution if we need to do differently in the future.
Thank you again @costas80

**Comment by costas80** [comment]
Thanks for the update @EliottPaillard. Good to see you found a workaround but do keep in mind a custom JSON validator instance if you end up having more complex validation needs (remember there's no coding involved with this, just configuration of the schemas and supported types of validation - that and of course running the validator as part of your Dockerised service).

I'll close this issue for now but feel free to reopen if anything related comes up.
